### ISSUE TITLE
Project not build in active configuration Visual Studio MacOS .net Core

### ISSUE THREAD

**Issue by AbhimanyuAryan** [dotnet/docs#1433]
I have created an Console Application(.Net Core) in Visual Studios MacOS Preview. In the project solution I don't see my program.cs also other things are not available it says *Project not built in active configuration*

[![enter image description here][1]][1]

whereas the project solution should look something like this

 [![enter image description here][2]][2]

I have installed [.net core for macOS][3]. Also done with Homebrew configurations. I already had openssl & openssl@1.1 installed in osx so when I try to re-install openssl with homebrew it says 

    Warning: openssl is a keg-only and another version is linked to opt.
    Use `brew install --force` if you want to install this version

  [1]: https://i.stack.imgur.com/kcEV0.png
  [2]: https://i.stack.imgur.com/Ywd8s.png
  [3]: https://www.microsoft.com/net/core#macos

**Comment by mairaw** [comment]
@richlander @blackdwarf I think this issue would be more appropriate on a different repo since it's not related to the docs per se. Any suggestion where we should move this? Or do you know why this happen?

**Comment by AbhimanyuAryan** [comment]
Yes I would like to know where to move this issue @mairaw

**Comment by blackdwarf** [comment]
The reinstall of openssl error simply says that that version or a newer one is present and that if the user wants that particular one, the `--force` switch to `brew install` will install it. It is not needed, if you have openssl 1.1 installed, all should be fine.

For the VS for Mac issue, I would need more data: 

1. What is the version?
2. Can it build at all? 
3. Can it run? 
4. Can we see the project that was made? 
5. What does `dotnet --version` on the command line say?

**Comment by blackdwarf** [comment]
Also, @AbhimanyuAryan if you want you can move this issue to dotnet/core and we can continue the discussion there.

**Comment by AbhimanyuAryan** [comment]
This issue is fixed http://stackoverflow.com/questions/41773344/project-not-build-in-active-configuration-visual-studio-macos-net-core

**Comment by Zhengchai** [comment]
The refereed solution doesn't work for .NETCORE 3.0.x and 3.1.x on VS2019 on Mac Catalina.
This problem still exist with above env.

I tried to debug found the generated ProjectGuid are same of the two projects. it is strange.

**Comment by ma-majumder** [comment]
Add missing entry for your project in *.sln file under **ProjectConfiguration**. There should be four entry for each project.

```
{PROJECT_GUI}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
{PROJECT_GUI}.Debug|Any CPU.Build.0 = Debug|Any CPU
{PROJECT_GUI}.Release|Any CPU.ActiveCfg = Release|Any CPU
{PROJECT_GUI}.Release|Any CPU.Build.0 = Release|Any CPU
```

In my solution file `{PROJECT_GUI}.Debug|Any CPU.Build.0 = Debug|Any CPU` was missing.
