### ISSUE TITLE
[Breaking change]: dotnet-sdk-6.0 broken dependency on Debian Buster

### ISSUE THREAD

**Issue by mbearup** [dotnet/docs#27559]
### Description

`dotnet-sdk-6.0` version `6.0.101` was published to `microsoft-debian-buster-prod` this week. It depends on `dotnet-targeting-pack-6.0 >= 6.0.1` but the latest version available is `6.0.0-1`. Since this dependency is not available, `dotnet-sdk-6.0.0` fails to install. Will `dotnet-targeting-pack-6.0` be updated to resolve this dependency?
```
The following packages have unmet dependencies:
 dotnet-sdk-6.0 : Depends: dotnet-targeting-pack-6.0 (>= 6.0.1) but 6.0.0-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

### Version

Other (please put exact version in description textbox)

### Previous behavior

Version `6.0.100-1` of the dotnet-sdk-6.0 package was installable. But version `6.0.101-1` is not.
```
# apt install dotnet-sdk-6.0=6.0.100-1
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  aspnetcore-runtime-6.0 aspnetcore-targeting-pack-6.0 dotnet-apphost-pack-6.0 dotnet-host dotnet-hostfxr-6.0 dotnet-runtime-6.0 dotnet-runtime-deps-6.0 dotnet-sdk-6.0
  netstandard-targeting-pack-2.1
...
Preparing to unpack .../8-dotnet-sdk-6.0_6.0.100-1_amd64.deb ...
Unpacking dotnet-sdk-6.0 (6.0.100-1) ...
...
Welcome to .NET!
```

### New behavior

```
The following packages have unmet dependencies:
 dotnet-sdk-6.0 : Depends: dotnet-targeting-pack-6.0 (>= 6.0.1) but 6.0.0-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

### Type of breaking change

- [X] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load/execute or different run-time behavior.
- [ ] **Source incompatible**: Source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK, such as compile errors or different run-time behavior.

### Reason for change

dotnet-targeting-pack-6.0 was not updated to match dotnet-sdk-6.0

### Recommended action

Publish updated version of dotnet-targeting-pack-6.0

### Feature area

SDK

**Comment by rbhanda** [comment]
The missing targeting pack is available at https://packages.microsoft.com/debian/10/prod/pool/main/d/dotnet-targeting-pack-6.0/ 
I believe this issue was resolved yesterday. Are you still seeing this error @mbearup

**Comment by leecow** [comment]
Just installed to a green buster image and the dotnet-sdk-6.0 setup succeeded. Looks like this was resolved yesterday.

**Comment by gewarren** [comment]
Thanks @rbhanda and @leecow. Closing this issue.

**Comment by tirelibirefe** [comment]
2023.January the new packages have still broken dependency .
```
The following packages have unmet dependencies:
 dotnet-sdk-7.0 : Depends: netstandard-targeting-pack-2.1 (>= 2.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by gewarren** [comment]
@adegeo Do you know where @tirelibirefe should log an issue about this?

**Comment by LudoTexx** [comment]
> 2023.January the new packages have still broken dependency .
> 
> ```
> The following packages have unmet dependencies:
>  dotnet-sdk-7.0 : Depends: netstandard-targeting-pack-2.1 (>= 2.1.0) but it is not installable
> E: Unable to correct problems, you have held broken packages.
> ```

Same problem here on 22.10.

**Comment by gewarren** [comment]
@adegeo Can you help here?

**Comment by adegeo** [comment]
Sorry for the delay. Generally, these resolve themselves as the targeting pack gets released. But if it's still not working, I would file an issue with https://github.com/dotnet/sdk/issues
