### ISSUE TITLE
Compiler error example generates another compiler error

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#7288]
Presented code example generates (in Visual Studio 15.8.1, Roslyn C# Compiler version 2.9.0.63208):
```
Error CS5001: Program does not contain a static 'Main' method suitable for an entry point
```

and not CS4009.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6873762-e2d6-1b55-d0cb-f623814d5a3f
* Version Independent ID: 13f25457-7546-1cc6-22e5-95519d2c395d
* Content: [Compiler Error CS4009](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs4009)
* Content Source: [docs/csharp/misc/CS4009.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/CS4009.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Fixed in PR #7287. Closing.

**Comment by pkulikov** [comment]
@rpetrusha sorry, but #7287 doesn't fix this issue. This issue is about the fact that the code given in the **CS4009** article produces **CS5001** compiler error.

**Comment by rpetrusha** [comment]
Ah. Sorry, I'd missed that, @pkulikov. I'll reopen.
