### ISSUE TITLE
Not able to save the result file name with --logger option

### ISSUE THREAD

**Issue by raghavendrabankapur** [dotnet/docs#8193]
When I pass the command line argument as --logger:trx;logfilename=full path of the log filename.trx,
the file is not getting saved in the location specified.

**Comment by Thraka** [comment]
@raghavendrabankapur Is this related to .NET Core? If so, what version are you using? Can you give me a full example of what you used for a path and where it went?

**Comment by mairaw** [comment]
[dotnet-test](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore21] has that parameter. Tagging @KathleenDollard and @livarcocc

**Comment by raghavendrabankapur** [comment]
@Thraka version of dotnet is 2.1.202 . The cli parameters i am passing are 
//Current working directory is the test project file path, then as below

dotnet test testproj.csproj --filter TestCategory=categoryname --logger "trx;logfilename=filepath for the result with extension .trx"

**Comment by raghavendrabankapur** [comment]
@Thraka  do we have any update for the same?

**Comment by Thraka** [comment]
Not yet, I'll ping the members referenced above on email.

**Comment by livarcocc** [comment]
Please, update to a newer version of the SDK, like 2.1.403. There is a good chance this issue has been addressed there. 2.1.202 is not longer supported.

Also, are you quoting your parameters? It seems like your path may contain white spaces in it.

**Comment by raghavendrabankapur** [comment]
@livarcocc I updated the version but still facing the same issue. Also there is no space in the request.

**Comment by livarcocc** [comment]
could you paste exactly the command you are using? Also, the output of `dotnet --info`.

And if possible, the contents of a csproj where this repros?

**Comment by Thraka** [comment]
@raghavendrabankapur Hi, just wanted to ping you on this 😄

**Comment by mairaw** [comment]
@raghavendrabankapur since we haven't heard back from you, we're closing the issue. If you're still experiencing this problem, please open a new issue at https://github.com/dotnet/cli since this is a product issue, not a documentation issue, it seems.
